import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
});

export const metadata = {
	title: "Cine Rental | Learn with Sumit",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className="dark"
		>
			<body
				className={`dark:bg-body bg-white font-[Sora] dark:text-white text-dark ${sora.className}`}
			>
				{children}
			</body>
		</html>
	);
}

